In [3]:
import pandas as pd
import numpy as np

In [4]:
movies = pd.read_csv('/Users/I578070/Desktop/100DaysML/Datasets/dataset-session-19/imdb-top-1000.csv')
deliveries = pd.read_csv('/Users/I578070/Desktop/100DaysML/Datasets/dataset-session-19/deliveries.csv')

In [5]:
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [6]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [7]:
genre = movies.groupby('Genre')
genre

In [8]:
genre.sum()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0

In [9]:
genre.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
6,Pulp Fiction,1994,154,Crime,8.9,Quentin Tarantino,John Travolta,1826188,107928762.0,94.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0
9,Fight Club,1999,139,Drama,8.8,David Fincher,Brad Pitt,1854740,37030102.0,66.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0
11,Forrest Gump,1994,142,Drama,8.8,Robert Zemeckis,Tom Hanks,1809221,330252182.0,82.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
15,Goodfellas,1990,146,Biography,8.7,Martin Scorsese,Robert De Niro,1020727,46836394.0,90.0
17,One Flew Over the Cuckoo's Nest,1975,133,Drama,8.7,Milos Forman,Jack Nicholson,918088,112000000.0,83.0
18,Hamilton,2020,160,Biography,8.6,Thomas Kail,Lin-Manuel Miranda,55291,440984783.0,90.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
20,Soorarai Pottru,2020,153,Drama,8.6,Sudha Kongara,Suriya,54995,556832648.0,NaN
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
22,Cidade de Deus,2002,130,Crime,8.6,Fernando Meirelles,Kátia Lund,699256,7563397.0,79.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
35,The Intouchables,2011,112,Biography,8.5,Olivier Nakache,Éric Toledano,760360,13182281.0,57.0
38,The Pianist,2002,150,Biography,8.5,Roman Polanski,Adrien Brody,729603,32572577.0,85.0
43,The Lion King,1994,88,Animation,8.5,Roger Allers,Rob Minkoff,942045,422783777.0,88.0
46,Hotaru no haka,1988,89,Animation,8.5,Isao Takahata,Tsutomu Tatsumi,235231,150734678.0,94.0
47,Back to the Future,1985,116,Adventure,8.5,Robert Zemeckis,Michael J. Fox,1058081,210609762.0,87.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
51,Modern Times,1936,87,Comedy,8.5,Charles Chaplin,Charles Chaplin,217881,163245.0,96.0
52,City Lights,1931,87,Comedy,8.5,Charles Chaplin,Charles Chaplin,167839,19181.0,99.0
56,Kimi no na wa.,2016,106,Animation,8.4,Makoto Shinkai,Ryûnosuke Kamiki,194838,5017246.0,79.0
58,Spider-Man: Into the Spider-Verse,2018,117,Animation,8.4,Bob Persichetti,Peter Ramsey,375110,190241310.0,87.0
64,3 Idiots,2009,170,Comedy,8.4,Rajkumar Hirani,Aamir Khan,344445,6532908.0,67.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
93,Inglourious Basterds,2009,153,Adventure,8.3,Quentin Tarantino,Brad Pitt,1267869,120540719.0,69.0
110,Das Boot,1981,149,Adventure,8.3,Wolfgang Petersen,Jürgen Prochnow,231855,11487676.0,86.0
114,2001: A Space Odyssey,1968,149,Adventure,8.3,Stanley Kubrick,Keir Dullea,603517,56954992.0,84.0
115,Per qualche dollaro in più,1965,132,Western,8.3,Sergio Leone,Clint Eastwood,232772,15000000.0,74.0
119,Vertigo,1958,128,Mystery,8.3,Alfred Hitchcock,James Stewart,364368,3200000.0,100.0
145,Shutter Island,2010,138,Mystery,8.2,Martin Scorsese,Leonardo DiCaprio,1129894,128012934.0,63.0
220,Kahaani,2012,122,Mystery,8.1,Sujoy Ghosh,Vidya Balan,57806,1035953.0,NaN
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
691,The Outlaw Josey Wales,1976,135,Western,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
712,Shadow of a Doubt,1943,108,Film-Noir,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0

In [10]:
genre.min()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,300,1924,45,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,33.0
Adventure,2001: A Space Odyssey,1925,88,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,41.0
Animation,Akira,1940,71,7.6,Adam Elliot,Adrian Molina,25229,128985.0,61.0
Biography,12 Years a Slave,1928,93,7.6,Adam McKay,Adrien Brody,27254,21877.0,48.0
Comedy,(500) Days of Summer,1921,68,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,45.0
Crime,12 Angry Men,1931,80,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,47.0
Drama,1917,1925,64,7.6,Aamir Khan,Abhay Deol,25088,3600.0,28.0
Family,E.T. the Extra-Terrestrial,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [11]:
#find the top 3 genre by total earning
movies.groupby('Genre').sum()['Gross'].sort_values(ascending=False)

Genre
Drama        3.540997e+10
Action       3.263226e+10
Comedy       1.566387e+10
Animation    1.463147e+10
Adventure    9.496922e+09
Crime        8.452632e+09
Biography    8.276358e+09
Mystery      1.256417e+09
Horror       1.034649e+09
Fantasy      7.827267e+08
Family       4.391106e+08
Film-Noir    1.259105e+08
Western      5.822151e+07
Thriller     1.755074e+07
Name: Gross, dtype: float64

In [12]:
# find the genere with higest avg IMDB rating
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending= False)

Genre
Western      8.350000
Crime        8.016822
Fantasy      8.000000
Mystery      7.975000
Film-Noir    7.966667
Drama        7.957439
Action       7.949419
Biography    7.938636
Adventure    7.937500
Animation    7.930488
Horror       7.909091
Comedy       7.901290
Family       7.800000
Thriller     7.800000
Name: IMDB_Rating, dtype: float64

In [13]:
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [14]:
#find director with most popularity
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False)

Director
Christopher Nolan    11578345
Quentin Tarantino     8123208
Steven Spielberg      7817166
David Fincher         6607859
Martin Scorsese       6513530
                       ...
J. Lee Thompson         26457
Peter Mullan            25938
René Laloux             25229
Francis Lee             25198
Kaige Chen              25088
Name: No_of_Votes, Length: 548, dtype: int64

In [15]:
#find the highest rated movie of each genre
movies.groupby('Genre')['IMDB_Rating'].max()

Genre
Action       9.0
Adventure    8.6
Animation    8.6
Biography    8.9
Comedy       8.6
Crime        9.2
Drama        9.3
Family       7.8
Fantasy      8.1
Film-Noir    8.1
Horror       8.5
Mystery      8.4
Thriller     7.8
Western      8.8
Name: IMDB_Rating, dtype: float64

In [16]:
# find the number of movies done by each user
movies['Star1'].value_counts()

Star1
Tom Hanks          12
Robert De Niro     11
Al Pacino          10
Clint Eastwood     10
Humphrey Bogart     9
                   ..
Preity Zinta        1
Javier Bardem       1
Ki-duk Kim          1
Vladimir Garin      1
Robert Donat        1
Name: count, Length: 660, dtype: int64

# grouby attributes and methods
find total number of groups -> len
find item in each group -> size
first()/last() vs filtering
groups 
describe 
sample 
nunique

In [17]:
len(movies.groupby('Genre'))

14

In [18]:
movies.groupby('Genre').nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [19]:
movies.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [20]:
genre.first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [21]:
genre.last()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [22]:
#finding the nth item
genre.nth(4)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
20,Soorarai Pottru,2020,153,Drama,8.6,Sudha Kongara,Suriya,54995,556832648.0,NaN
22,Cidade de Deus,2002,130,Crime,8.6,Fernando Meirelles,Kátia Lund,699256,7563397.0,79.0
38,The Pianist,2002,150,Biography,8.5,Roman Polanski,Adrien Brody,729603,32572577.0,85.0
58,Spider-Man: Into the Spider-Verse,2018,117,Animation,8.4,Bob Persichetti,Peter Ramsey,375110,190241310.0,87.0
64,3 Idiots,2009,170,Comedy,8.4,Rajkumar Hirani,Aamir Khan,344445,6532908.0,67.0
114,2001: A Space Odyssey,1968,149,Adventure,8.3,Stanley Kubrick,Keir Dullea,603517,56954992.0,84.0
220,Kahaani,2012,122,Mystery,8.1,Sujoy Ghosh,Vidya Balan,57806,1035953.0,NaN
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0

In [23]:
genre.get_group('Horror')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
707,The Innocents,1961,100,Horror,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
844,Halloween,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
876,The Invisible Man,1933,71,Horror,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0

In [25]:
#agg method
genre.agg(
    {
        'Runtime':'mean',
        'No_of_Votes':'sum',
        'IMDB_Rating':'mean'
    }
)

              Runtime  No_of_Votes  IMDB_Rating
Genre
Action     129.046512     72282412     7.949419
Adventure  134.111111     22576163     7.937500
Animation   99.585366     21978630     7.930488
Biography  136.022727     24006844     7.938636
Comedy     112.129032     27620327     7.901290
Crime      126.392523     33533615     8.016822
Drama      124.737024     61367304     7.957439
Family     107.500000       551221     7.800000
Fantasy     85.000000       146222     8.000000
Film-Noir  104.000000       367215     7.966667
Horror     102.090909      3742556     7.909091
Mystery    119.083333      4203004     7.975000
Thriller   108.000000        27733     7.800000
Western    148.250000      1289665     8.350000

In [27]:
#looping on groups
for group,data in genre:
    print(data[data['IMDB_Rating'] == data['IMDB_Rating'].max()])

      Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
2  The Dark Knight          2008      152  Action          9.0

            Director           Star1  No_of_Votes        Gross  Metascore
2  Christopher Nolan  Christian Bale      2303232  534858444.0       84.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
21  Interstellar          2014      169  Adventure          8.6

             Director                Star1  No_of_Votes        Gross  \
21  Christopher Nolan  Matthew McConaughey      1512360  188020017.0

    Metascore
21       74.0
                     Series_Title Released_Year  Runtime      Genre  \
23  Sen to Chihiro no kamikakushi          2001      125  Animation

    IMDB_Rating        Director          Star1  No_of_Votes       Gross  \
23          8.6  Hayao Miyazaki  Daveigh Chase       651376  10055859.0

    Metascore
23       96.0
       Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
7  Schindler's List          1993      195  Biography          8.9

           Director        Star1  No_of_Votes       Gross  Metascore
7  Steven Spielberg  Liam Neeson      1213505  96898818.0       94.0
       Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
19     Gisaengchung          2019      132  Comedy          8.6
26  La vita è bella          1997      116  Comedy          8.6

           Director            Star1  No_of_Votes       Gross  Metascore
19     Bong Joon Ho     Kang-ho Song       552778  53367844.0       96.0
26  Roberto Benigni  Roberto Benigni       623629  57598247.0       59.0
    Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
1  The Godfather          1972      175  Crime          9.2

               Director          Star1  No_of_Votes        Gross  Metascore
1  Francis Ford Coppola  Marlon Brando      1620367  134966411.0      100.0
               Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
0  The Shawshank Redemption          1994      142  Drama          9.3

         Director        Star1  No_of_Votes       Gross  Metascore
0  Frank Darabont  Tim Robbins      2343110  28341469.0       80.0
                            Series_Title Released_Year  Runtime   Genre  \
688           E.T. the Extra-Terrestrial          1982      115  Family
698  Willy Wonka & the Chocolate Factory          1971      100  Family

     IMDB_Rating          Director         Star1  No_of_Votes        Gross  \
688          7.8  Steven Spielberg  Henry Thomas       372490  435110554.0
698          7.8        Mel Stuart   Gene Wilder       178731    4000000.0

     Metascore
688       91.0
698       67.0
                     Series_Title Released_Year  Runtime    Genre  \
321  Das Cabinet des Dr. Caligari          1920       76  Fantasy

     IMDB_Rating      Director          Star1  No_of_Votes        Gross  \
321          8.1  Robert Wiene  Werner Krauss        57428  337574718.0

     Metascore
321        NaN
      Series_Title Released_Year  Runtime      Genre  IMDB_Rating    Director  \
309  The Third Man          1949      104  Film-Noir          8.1  Carol Reed

            Star1  No_of_Votes     Gross  Metascore
309  Orson Welles       158731  449191.0       97.0
   Series_Title Released_Year  Runtime   Genre  IMDB_Rating          Director  \
49       Psycho          1960      109  Horror          8.5  Alfred Hitchcock

              Star1  No_of_Votes       Gross  Metascore
49  Anthony Perkins       604211  32000000.0       97.0
   Series_Title Released_Year  Runtime    Genre  IMDB_Rating  \
69      Memento          2000      113  Mystery          8.4
81  Rear Window          1954      112  Mystery          8.4

             Director          Star1  No_of_Votes       Gross  Metascore
69  Christopher Nolan     Guy Pearce      1125712  25544867.0       80.0
81   Alfred Hitchcock  James Stewart       444074  36764313.0      100.0
        Series_Title Released_Year  Runtime     Genre  IMDB_Rating  \
700  Wait Until Dark          1967      108  Thriller          7.8

          Director           Star1  No_of_Votes       Gross  Metascore
700  Terence Young  Audrey Hepburn        27733  17550741.0       81.0
                       Series_Title Released_Year  Runtime    Genre  \
12  Il buono, il brutto, il cattivo          1966      161  Western

    IMDB_Rating      Director           Star1  No_of_Votes      Gross  \
12          8.8  Sergio Leone  Clint Eastwood       688390  6100000.0

    Metascore
12       90.0

In [28]:
#split apply combine

genre.apply(min)

/var/folders/gm/nbsrp6ks1gnb1c4z3v9rvb4r0000gn/T/ipykernel_43565/2745402299.py:3: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  genre.apply(min)
/var/folders/gm/nbsrp6ks1gnb1c4z3v9rvb4r0000gn/T/ipykernel_43565/2745402299.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(min)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,,
Action,300,1924,45,Action,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,NaN
Adventure,2001: A Space Odyssey,1925,88,Adventure,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,NaN
Animation,Akira,1940,71,Animation,7.6,Adam Elliot,Adrian Molina,25229,128985.0,NaN
Biography,12 Years a Slave,1928,93,Biography,7.6,Adam McKay,Adrien Brody,27254,21877.0,NaN
Comedy,(500) Days of Summer,1921,68,Comedy,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,NaN
Crime,12 Angry Men,1931,80,Crime,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,NaN
Drama,1917,1925,64,Drama,7.6,Aamir Khan,Abhay Deol,25088,3600.0,NaN
Family,E.T. the Extra-Terrestrial,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,Fantasy,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,Film-Noir,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,Horror,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,Mystery,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,NaN
Thriller,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,Western,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [32]:
# find the number of movies that start with a

def foo(group):
    df = group[group['Series_Title'].str.startswith('A')]
    return df.count()

In [33]:
genre.apply(foo)

/var/folders/gm/nbsrp6ks1gnb1c4z3v9rvb4r0000gn/T/ipykernel_43565/2031851770.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(foo)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,,
Action,10,10,10,10,10,10,10,10,10,6
Adventure,2,2,2,2,2,2,2,2,2,2
Animation,2,2,2,2,2,2,2,2,2,1
Biography,9,9,9,9,9,9,9,9,9,7
Comedy,14,14,14,14,14,14,14,14,14,11
Crime,4,4,4,4,4,4,4,4,4,3
Drama,21,21,21,21,21,21,21,21,21,18
Family,0,0,0,0,0,0,0,0,0,0
Fantasy,0,0,0,0,0,0,0,0,0,0
Film-Noir,0,0,0,0,0,0,0,0,0,0
Horror,1,1,1,1,1,1,1,1,1,1
Mystery,0,0,0,0,0,0,0,0,0,0
Thriller,0,0,0,0,0,0,0,0,0,0
Western,0,0,0,0,0,0,0,0,0,0

In [36]:
#find ranking of each movie in the group according to IMDB score

def rank_movie(group):
    group['IMDB_Rating'].rank(ascending= True)
    return group

genre.apply(rank_movie)

/var/folders/gm/nbsrp6ks1gnb1c4z3v9rvb4r0000gn/T/ipykernel_43565/1778140590.py:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(rank_movie)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

[1000 rows x 10 columns]

In [ ]:
#group by using multiple column

df1 = movies.groupby(['Director','Star1'])

In [40]:
df1.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [ ]:
#most earning director-actor combo
df1['Gross'].sum().sort_values(ascending= False)

Director              Star1
Akira Kurosawa        Toshirô Mifune     2.999877e+09
Anthony Russo         Joe Russo          2.205039e+09
Billy Wilder          William Holden     1.286779e+09
Christopher Nolan     Christian Bale     1.242940e+09
Werner Herzog         Klaus Kinski       1.124605e+09
                                             ...
Jeong-beom Lee        Won Bin            6.460000e+03
Shane Meadows         Paddy Considine    6.013000e+03
Jaco Van Dormael      Jared Leto         3.600000e+03
Thomas Jahn           Til Schweiger      3.296000e+03
Anders Thomas Jensen  Ulrich Thomsen     1.305000e+03
Name: Gross, Length: 898, dtype: float64

In [43]:
#find the best(int terms if metascore(avg)) actor genre-combo
movies.groupby(['Genre','Star1'])['Metascore'].mean().sort_values(ascending=False)

Genre      Star1
Drama      Humphrey Bogart             100.0
Adventure  Peter O'Toole               100.0
Drama      Bertil Guve                 100.0
Mystery    James Stewart               100.0
Drama      Orson Welles                100.0
                                       ...
Fantasy    Werner Krauss                 NaN
Mystery    Bernard-Pierre Donnadieu      NaN
           Jose Coronado                 NaN
           Laurence Olivier              NaN
           Vidya Balan                   NaN
Name: Metascore, Length: 829, dtype: float64